language: c

compiler:
  - clang
  - gcc

sudo: required

env:
  global:
    # BINTRAY_USER
    - secure: "n8X1UB89HJlRqAd3qrUfVhULz/JBRkdq/SnmmMjTF7ELbKWY7v8JQq4lze2jJQlor/2A//qQOcIrpUiuyWxYY3+nvXSzxBY2TtCIjRdVwzRoQiFYDoR7Fnay7T060RnZJ5ti5iarlQfPtVCh0s0dFocT6+mTZYdxUY5glWR5fgy3TNlZFXmXs/qZUdqOPCCg01NZObz9ZGdpnc+9NLi3liBcG4Sh2Fdj/1yY8qIGWEQiOKQiTCGozKFXDw0Dg8uFEC84aW873Cm1g+IxeIs967UK/IjeTxVXYE+R0WwfIIIgfONIzvWwpIIuc+a7XXCZkHqFGqvU9Hx6M2b5z5W7r2i18YmXVRyIoyVmabDCxWzIVDleYN0EsOr57gMV4c5z4mLTtmLb9mIPjpLbitzilzNCckVhwSIm56PwXrHR+19D+9WpgO81oP2eIIA+G6uCZfEyj5uTZCc19G2t18GWwJ+bwYKMly9tdwLcC2JaKmC2pxUgouiwxDKQBly/1OGxeGNXPVoX4ZuShPtUYO0huSQXEwyghpUDuYERBqtiavwZO7uTLO7RT45JhRWCZKUN9njQISQiQJbusyswElHTwGwEBypB58S34C2hmvW9Eh0exQOkLAe6bizwu5HyARw0C87zJ+NH/CQaT630MKKRqpZtzgvrTnMBSqRN1k1sU7E="
    # BINTRAY_API_KEY
    - secure: "Q1axFjBkrtLgLW/9x+hTYWH3RsoWJ5xFPiO5v4Cdzf73nEsnPjl6YsawWRqk9KGp6uINbtOguic+Mt9+4jGxk5O/64DcKh5FWqNf1FX7K6Qzd6mCvo0hxffmBzOyP53n8799AcVLmcEaOXhbtg7zBgXTn3cvbVUeR9m4HGgOE/6Zvb6ubp+1itBQTI6l9oHeggA0L4ebxdaBG1KSJI4ZQzBO+3Bn1kDHPa1HUkaeE9htCa175Z/8kXTzVUhLiWmRiDRh96KgS0Ccj0KldHFASDSsKztV2GKgxShZYvpy8akXvMuW6Y0V1Jii4rrBFa0/FXSmk0i4S6RlAkPCYOFndYUth8Dm6O18W41iHb+q1UZB0hZ4+w8PHs3maVajaSl2iiVOGUm8g1hSNodIFPlPsy7F2ZpAeDVpT8KEKQ0lWoOyqdUl7EZK/ojX15UTRnQBx0fqi3hgWLAhstpJOC5fXQELG4BSl87AkXCcyP7WsyEiMUvTbU5GD2fWy2mzUQRH5u3ReDVsShtp+Pl2Rt7hxwBRayTWS7qt54f76A+GIkBSYBRJyGNdvq4c/e0O6oDhqBvstfDt6MEYF1FGYPRLdP4PRGnyLIOzZPbPl2h4D2UYkPJ9TlVCAf24IDN7mHubJJPc6GwFWRju17oyJSwX8Gi5+JViM0qO9Xxvj1fWVPI="
    # BINTRAY_REPO_OWNER
    - secure: "FnG6SR89DCH9V+zf6RqVqvRFpAbhcH92CwQRW+Jjo+/WHTFUzQc0ndp7jHeaj7M0LNxJeEn66GprmmE1Fqa4Is6k1T97XNB8IQu1rttHbo4xxwmP2Jewzv2q3PbDdnYsySPfH1rzizbohu7b1M9NNcIt3/2zsyOKfa8lfHvBQEo="

arch:
  packages:
    - qt5-declarative
    - glib2
    - clang
    #- clazy-git
    - xorg-server-xvfb
  script:
    - export CLAZY_CHECKS="level1"
    - mkdir build
    - if [ "$CC" = "gcc" ]; then cd build && qmake -spec linux-g++ CONFIG+=use_qt_paths ../qtgsettings.pro; fi
    #- if [ "$CC" = "clang" ]; then cd build && qmake -spec linux-clang CONFIG+=use_qt_paths QMAKE_CXX="clazy" ../qtgsettings.pro; fi
    - if [ "$CC" = "clang" ]; then cd build && qmake -spec linux-clang CONFIG+=use_qt_paths ../qtgsettings.pro; fi
    - cd build && make -j$(nproc)
    - cd build && xvfb-run -a -s "-screen 0 800x600x24" make check
    - ./.travis/bintray-wrapper.sh

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

deploy:
  provider: bintray
  on:
    branch: master
    condition: "$CC = gcc"
  file: cibuild/bintray.json
  user:
    secure: "dcMhE0W1Ecy1RGJpfUcpsDaF5dnFFLemTRzz68bxNk2zakM3aBBMjnpqFHwXUQgxj3Xhnxx2pyh61Oc36aFQ4Aw1hmfRNn7C7vch6VA8tlNoJLgmR50NKyOnjCRKZo478crdKvEZey2i1nP3iBa61hD1iWwJg+3XZ89W4wnGmVnSDpI05/rb9iUXSFLliZV2c9a4cmptZHvqN1PuBHTeEtr5A9SPWT9cR6PfzcVUYnWqUVk/PG3FKL+GkA9Qj/Fj1nuDIMzrqCKPUAqW1a1h/AO7YXn1kNLgUPk3cQngDkmukMBzjrqsnoYD24eXwnRsQhiJfYyBBr4cawSa/GzWyT65NCJuVvr147XSj/eMHSS8dU2xOQamVwdi1AMixTKeXq17z3gTI8bSOMj7kaYz3GEHJhDHM2DV8lYpaJ7thh6W1H6bNxYOj06sTMKxdh+4rhBLpJBFb6hMm3P/RBdz1ZkBYceakcG3l3amlZNpaWYTKBjicHs96tQ1g9JbL/OFhlFqwp4H/IIGRaBzvCy+GJMhTz9PVAd9hbA8kNCZ9IYFDQGJTIFUx7eFbbks1XJcWLOG6yNW8ywfvtEAr2obWigVytFS6jD7xDUlkHjSluY0IHkXRoB22+tMxpXZ+8y4szow3aABJ8pIWGSRJU3P9wNQFUGepdv3N+yZUMMqK2o="
  key:
    secure: "TgUvT02pmz475NLu4VgwMy0UNsg/vrAM1XhYyBpwjDt/PjIkS/Vvf6aiH9RqahmfkeiQPy0KGXelUvcQeqrrmHl/jaJwT312BLgAqzeXKbVzJmX97Jyw2zyYFjGQQ81cUI08y7ZLVCju1zt+xD9HZWAxgFEbvy5AqoZTZjXLjyXU2xeo6VPy9pHKgmXM8DIs1FvzdDelksOvZMaZrVvT5KE4CgD+9sXWdhRBb9pnNEm/sg0DOIUv41cNpqKsXnTfbEJrSwVbcWWvdnFt5fblMRpOl/4nfQIDvWd3KDJBqKl2RW47YxJ50dX+b2khL1vxbqJPunZdjsm1yphZECtfMvBEjegBGUuyQ3KKcDw+yDHZ1BSfwdN+3Ta6Z1okcfsLhkNVMa6RWnfuhr6pnRf1gPWlYfiZX1lvPvHp45bGWAq/Vx3AVr63tbhNN6COk/cZgUfemdX8PPb+KHtGTsl4+4BgvtlxZUluw0GalWr5A4bjNDyy4+6VKePotGI4Ta4LgSxG8TQqyx4WUzSNkTMBZlSz8d4gdYaxoCpPRTYvhYVvxd1IKybRJ0P2Y5cEuevVojGQCnXikTYuBcb47qDQdJEGGgJ8LTRevqz3FdHHVb+Xk1xlRTs6ADYyuNcEs9j+2/Xp6jSe5GsALc7NU/zX49VidQyDuXfxlcs6PnWTVe4="

notifications:
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
